### ISSUE TITLE
[BUG] Visitor's number isn't increasing

### ISSUE THREAD

**Issue by mrhrifat** [Nathan13888/VisitorBadgeReloaded#15]
**Describe the bug**
I am using **Profile Visitors Badges** with GitHub since 1.5 month. From last some days the visitors number got stuck at `2037` now last 2 days it's on `2047`. The problem of badge are 
- The number isn't increasing although I reload my GitHub profile. 
- But whenever I take only the link of badge & open it on a new tab & reload it, the number is increasing.

**Note:** I think, the visitors number don't increase with new visitor's, it increase by browser reload. Am I right?
- Link of my used badge
```
https://visitor-badge-reloaded.herokuapp.com/badge?page_id=mrhrifat&color=55acb7&style=for-the-badge&logo=Github
```

**Expected behavior**
As like as before, Whenever the browser will be reload the number of visitor would be increased or when someone visit the number will increase.

**Screenshots**
- This is on my GitHub profile
![image](https://user-images.githubusercontent.com/45077312/148650303-9242388f-9617-42ea-aea9-6d74f481df8b.png)
- This is on Browser Tab
![image](https://user-images.githubusercontent.com/45077312/148650894-c83ed30b-6b18-408e-a76d-2c1463acb4f1.png)

**Desktop (please complete the following information):**
 - OS: Linux 20.4
 - Browser Firefox
 - Version 95.0.1

**Comment by Nathan13888** [comment]
I suspect whether this issue could be related to the way github's camo server caches the badge. Have you looked into the expiry headers that is returned from the badge?

**Comment by Nathan13888** [comment]
@mrhrifat read #8

**Comment by mrhrifat** [comment]
I do not understand some points. What can be done to solve it now or is it not solvable now?

**Comment by Nathan13888** [comment]
Refer to the latest commit from yesterday.

**Comment by mrhrifat** [comment]
Thanks for your collaboration.
