### ISSUE TITLE
vbr.wocr.tk is down

### ISSUE THREAD

**Issue by Jirafey** [Nathan13888/VisitorBadgeReloaded#26]
vbr.wocr.tk is down

**Comment by Nathan13888** [comment]
Should be fixed now...

Seems like the container crashed when CountAPI went down... (probably going to deploy my own storage backend in the future...)

**Comment by Jirafey** [comment]
oh yeah, works perfectly! Thanks.

**Comment by Nathan13888** [comment]
Awesome! Good to hear!
