### ISSUE TITLE
Associate a github projects to manage TODOs as issues.

### ISSUE THREAD

**Issue by HariKishorePec** [Nathan13888/VisitorBadgeReloaded#3]
Instead of adding all your issues as TODOs, can you/we add them as issues and then add them to github projects? It would make it easy to maintain. I am excited to add not-so-core features(as of now, but will) but definitely, can contribute to first feature i.e., creating website.

P.S. - Recently got interest in contributing and collaborating as in open source, so thought, why not give it a shot. and, reached your repo from your link in your issue created in vistors-badge :). Have a nice day.

**Comment by Nathan13888** [comment]
This sounds like a good idea. I haven't been working on this project lately but plan to continue development once I get time to.

Meanwhile, I'd gladly accept any pull requests and provide any support for issues related to the project.

The other thing is that my current CI setup is kinda borked so I need to fix that as well haha.
