### ISSUE TITLE
Colour vs Color

### ISSUE THREAD

**Issue by alexlostorto** [Nathan13888/VisitorBadgeReloaded#37]
It is definitely not good practice to use **BOTH** spellings...

Please choose one version and use it everywhere.

PS: I am English and I also use 'colour' too LOL

### Example conflicts in [**badges.go**](https://github.com/Nathan13888/VisitorBadgeReloaded/blob/master/badges.go)

![image](https://github.com/Nathan13888/VisitorBadgeReloaded/assets/114829362/23e0bf57-8463-4c09-b82f-7a21d44cd537)
![image](https://github.com/Nathan13888/VisitorBadgeReloaded/assets/114829362/78367d7f-bd99-4bb8-9d15-020d07a2ac02)

**Comment by Nathan13888** [comment]
It should be consistent within the code base though.
