### ISSUE TITLE
[FEATURE] Optional Incrementation

### ISSUE THREAD

**Issue by alexlostorto** [Nathan13888/VisitorBadgeReloaded#38]
### Problem
To give an example, by adding several badges on one page, which all send their own GET request, every time someone views the page, the counter will increment by the same number as the number of badges. In this case, 21 times (including the badge in the description). 

<img width="499" alt="image" src="https://github.com/Nathan13888/VisitorBadgeReloaded/assets/114829362/190252be-5e25-453e-9dae-9b69c5d4f29d">

### Solution
No incrementation by default and instead use a parameter to control whether the counter should increment. Or perhaps use the /hit suburl as did CountAPI.

#### Current URL
```
https://vbr.wocr.tk/badge?page_id=[PAGE_ID]&[OPTIONAL_PARAMETER]
```

#### Proposed URL
```
https://vbr.wocr.tk/badge?page_id=[PAGE_ID]&[OPTIONAL_PARAMETER]&hit=true
```

**or**

```
https://vbr.wocr.tk/badge/hit?page_id=[PAGE_ID]&[OPTIONAL_PARAMETER]
```

**Comment by Nathan13888** [comment]
Hi Alex, thanks for the suggestion! I like your idea.

Just to confirm, so what should the "effect" of this flag be? Would **20 of the badges** with the `hit` flag set to anything but true, or if it's *empty* should not increment the counter by instead just return the existing badge count?

**Comment by alexlostorto** [comment]
This is your project so it's completely up to you, but I believe the flag should work as follows:

`hit=true` increment the counter
`hit=null` (empty) just return the current count

**Comment by Nathan13888** [comment]
Deployed latest update to prod!
