### ISSUE TITLE
The service is down

### ISSUE THREAD

**Issue by JunweiLiang** [Nathan13888/VisitorBadgeReloaded#44]
The service from my side seems down. Do you have any idea how this could be resolved? Thanks!

![Screenshot 2023-09-17 at 10 15 54](https://github.com/Nathan13888/VisitorBadgeReloaded/assets/22200250/49e7714e-fb8e-4d3e-8638-1c5b279ef2e7)
[link](https://vbr.wocr.tk/badge?page_id=JunweiLiang.JunweiLiang&right_color=green)

**Comment by Nathan13888** [comment]
Sorry the VM I run this on keeps running out of storage every few months since the log files get really big. The issue will be addressed in the near future once I finally move hosting :/

**Comment by Nathan13888** [comment]
I'll move hosting in a few weeks but I just haven't gotten around to doing it... sorry

**Comment by JunweiLiang** [comment]
Awesome! Thanks for the great work!
