### ISSUE TITLE
[FEATURE] Unique visits

### ISSUE THREAD

**Issue by cgarrovillo** [Nathan13888/VisitorBadgeReloaded#8]
**Is your feature request related to a problem? Please describe.**
The value of the badge is easily gone when a visitor refreshes the page to verify functionality.  It's clear that anyone can just spam refresh and the counter will go up

**Describe the solution you'd like**
It would be cool to track unique visitors instead.  I'm not sure how it would work exactly, but other offerings such as https://github.com/puf17640/git-badges have this behaviour i think

**Describe alternatives you've considered**
https://github.com/puf17640/git-badges

and adding a &cache=on query

**Additional context**
<img width="505" alt="image" src="https://user-images.githubusercontent.com/6688713/126268791-fa50d5fd-00db-4652-bc17-4e1ac1278c62.png">

Left is git-badges
Right is VBR

**Comment by Nathan13888** [comment]
I agree and it was something I intended on fixing. But the question is **how** should I detect that? 🤔

You are correct that `puf17640 /git-badges` does have this behaviour.

**Comment by Nathan13888** [comment]
Refer to line 41 of https://github.com/puf17640/git-badges/blob/master/server.js

**Comment by Nathan13888** [comment]
It defaults to caching now. So reloading on GH won't double count.

I will consider this issue/enhancement resolved now.
